//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogTema.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogTemplateEntities : DbContext
    {
        public BlogTemplateEntities()
            : base("name=BlogTemplateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLAyarlar> TBLAyarlar { get; set; }
        public virtual DbSet<TBLBlog> TBLBlog { get; set; }
        public virtual DbSet<TBLTiklama> TBLTiklama { get; set; }
        public virtual DbSet<TBLYorumlar> TBLYorumlar { get; set; }
    }
}
