//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogTema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAyarlar
    {
        public int ID { get; set; }
        public string BloggerAdi { get; set; }
        public string KisaAciklama { get; set; }
        public string Aciklama { get; set; }
        public string twitter { get; set; }
        public string linkedin { get; set; }
        public string facebook { get; set; }
        public string stackoverflow { get; set; }
        public string Yotube { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
    }
}
