//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogTema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBlog
    {
        public int ID { get; set; }
        public string BlogAdi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> Okunma { get; set; }
        public Nullable<int> Begenme { get; set; }
        public Nullable<int> Begenmeme { get; set; }
        public string Resim { get; set; }
    }
}
