//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogTema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLYorumlar
    {
        public int ID { get; set; }
        public Nullable<int> BlogID { get; set; }
        public string YorumYapan { get; set; }
        public string Yorum { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> Onay { get; set; }
    }
}
